### ISSUE TITLE
Fix Unnecessary Arg in Event Handler's event.execute

### ISSUE THREAD

**Issue by FadTheChad** [pranshu05/Elpha#4]
Why are you passing an array of commands in event.run param??

**Comment by pranshu05** [comment]
Because I am﻿ collecting the event by
`client.once(event.name, (...args)`

**Comment by FadTheChad** [comment]
Why are you passing the **commands** array in the **event**.execute function

**Comment by FadTheChad** [comment]
```js
 
 ​    ​if​ ​(​event​.​once​)​{ 
 ​        ​client​.​once​(​event​.​name​,​ ​(​...​args​)​ ​=>​ ​event​.​execute​(​...​args​,​ ​commands​)​) 
 ​    ​}​ ​else​ ​{ 
 ​        ​client​.​on​(​event​.​name​,​ ​(​...​args​)​ ​=>​ ​event​.​execute​(​...​args​,​ ​commands​)​) 
 ​    ​}
```

`commands`

**Comment by pranshu05** [comment]
commit in my repo...make changes which u feel right....repo is an opensource feel free to pull request

**Comment by FadTheChad** [comment]
Im on my phone rn so can't. 

Basically

1) replace the command array in the event.execute with client

2) Remove your application deploy function bin ready.js, and make it used inna developer command BECAUSE you are basically redeploying the commands every single time you reload the bot, whereas you should do it only if you update the slash cmds

**Comment by pranshu05** [comment]
Done

**Comment by FadTheChad** [comment]
Why did you remove the ...args, i said only the commands array lol, plus that would of errored so i recommend testing the bot before committing

**Comment by FadTheChad** [comment]
You also have to do point number 2 i stated above for the bot to run the ready event

**Comment by pranshu05** [comment]
oops
