### ISSUE TITLE
Update the README.md

### ISSUE THREAD

**Issue by the-amazing-atharva** [pranshu05/Elpha#48]
Hi there!

I would like to work on the README of this project to make it more appealing.
I would also add a CODE OF CONDUCT AND CONTRIBUTING guide for professional appeal.

If you liked my suggestions, do assign me this issue

**Comment by pranshu05** [comment]
Hey, You can raise a PR...I'll merge it!

**Comment by the-amazing-atharva** [comment]
Thanks for the reply
Working on it gradually
