### ISSUE TITLE
Avoid GuildMemberManager#cache.get

### ISSUE THREAD

**Issue by FadTheChad** [pranshu05/Elpha#7]
You seem to do members.cache.get multiple times. Cache is unreliable. Hence you should use GuildMemberManager#fetch instead which returns a Promise of a Member (don't forget to .catch)

**Comment by pranshu05** [comment]
ok....can u address the file in which its multiple time

**Comment by FadTheChad** [comment]
Try checking every file where you require getting a user/member, like moderation commands etc

**Comment by pranshu05** [comment]
Ok
